//
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
// ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
// THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
// PARTICULAR PURPOSE.
//
// Copyright (c) Microsoft Corporation. All rights reserved.
//

DEFINE_GUID(CLSID_CSample, 0x89c01448, 0x4d96, 0x44f4, 0x9d, 0xca, 0x2a, 0xc6, 0x19, 0x00, 0xcc, 0x4f);
